#pragma once

#define assert(condition) ; //then assert checks if its argument (which must have scalar type) compares equal to zero. 
#define halt() for(;;); //looping



/*
 * Initialize the virtual memory system and enable it
 */
void paging_init();

/*
 * Maps a memory address such that the virtual and physical addresses are identical
 */
void paging_map_identity_page(void* addr, int size);



/*The difference between logical and physical address is that logical address is generated by CPU during a program execution whereas, the physical address refers to a location in the memory unit.*/

/*Right now we have physical address mapping */
